namespace: wescale
resources:
  - ../base
images:
  - name: "gbloquel/microservices-demo-article-service"
    newName: "ghcr.io/ddrugeon/microservices-demo/article-service"
    newTag: latest
  - name: "gbloquel/microservices-demo-cart-service"
    newName: "ghcr.io/ddrugeon/microservices-demo/cart-service"
    newTag: latest
  - name: "gbloquel/microservices-demo-frontend-admin"
    newName: "ghcr.io/ddrugeon/microservices-demo/frontend-admin"
    newTag: latest
  - name: "gbloquel/microservices-demo-frontend-user"
    newName: "ghcr.io/ddrugeon/microservices-demo/frontend-user"
    newTag: latest
  - name: "gbloquel/microservices-demo-nginx-otel"
    newName: "nginx"
    newTag: "1.19"
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cart-service
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: article-service
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: microservices-redis
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: microservices-mongo
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: front-admin
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: front-user
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: reverse-proxy
  path: patch.yaml
