---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-admin-config
  namespace: "application"
data:
  endpoints.json: |
    {
      "apiArticlesEndpoint": "http://microservices.127.0.0.1.nip.io/api-article/article",
      "otelEndpoint": "http://otel.127.0.0.1.nip.io/v1/traces"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-user-config
  namespace: "application"
data:
  endpoints.json: |
    {
      "apiArticlesEndpoint": "http://microservices.127.0.0.1.nip.io/api-article/article",
      "apiCartEndpoint": "http://microservices.127.0.0.1.nip.io/api-cart/cart",
      "otelEndpoint": "http://otel.127.0.0.1.nip.io/v1/traces"
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-global-conf
  namespace: application
data:
  nginx.conf: |

    events {
      worker_connections  1024;
    }

    http {
      include    /etc/nginx/mime.types;
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

      sendfile     on;
      keepalive_timeout 65;

      include /etc/nginx/conf.d/*.conf;
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: reverse-proxy-config
  namespace: "application"
data:
  default.conf: |
    server {
      listen 80;
      index index.html index.htm;

      location / {
          add_header 'Access-Control-Allow-Origin' '*';
          proxy_pass http://front-user/;
          proxy_buffering off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
      }

      location /admin/ {
          proxy_pass http://front-admin/;
          proxy_buffering off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
      }

      location /api-article/ {
          proxy_pass http://article-service:8080/;
          proxy_buffering off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
      }

      location /api-cart/ {
          proxy_pass http://cart-service:8081/;
          proxy_buffering off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
      }
    }
#  opentelemetry_module.conf: |
#    NginxModuleEnabled ON;
#    NginxModuleOtelSpanExporter otlp;
#    NginxModuleOtelExporterEndpoint simplest-collector:4317;
#    NginxModuleServiceName reverse-proxy;
#    NginxModuleServiceNamespace application;
#    NginxModuleServiceInstanceId NGinxInstance-1;
#    NginxModuleResolveBackends ON;
#    NginxModuleTraceAsError ON;
---
