#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: microservices-ingress
#  namespace: "application"
#  annotations:
#    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "https://otel.127.0.0.1.nip.io/v1/traces"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, OPTIONS"
#    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"
#  labels:
#    app.kubernetes.io/name: ingress
#    app.kubernetes.io/instance: microservices
#spec:
#  rules:
#  - host: "microservices.127.0.0.1.nip.io"
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: reverse-proxy
#            port:
#              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: article-api-ingress
  namespace: "application"
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: microservices-article-api
  annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "microservices.127.0.0.1.nip.io"
    http:
      paths:
      - path: /api-article(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: article-service
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cart-api-ingress
  namespace: "application"
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: microservices-cart-api
  annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "microservices.127.0.0.1.nip.io"
    http:
      paths:
      - path: /api-cart(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: cart-service
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-user-ingress
  namespace: "application"
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: front-user
spec:
  rules:
  - host: "microservices.127.0.0.1.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-user
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-admin-ingress
  namespace: "application"
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: front-admin
  annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "microservices.127.0.0.1.nip.io"
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: front-admin
            port:
              name: http
