apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: "application"
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: microservices
type: Opaque
data:
  password: S3ViZXJuZXRlc1RyYWluaW5n
