---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-mongodb
  namespace: "application"
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: microservices
automountServiceAccountToken: false
