resources:
- ../base/
- ingress.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: emoji
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: voting
  path: patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vote-bot
  path: patch.yaml
