apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: demo-vector
servers: 1
agents: 2
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6445"
image: rancher/k3s:v1.27.4-k3s1
network: demo-net
ports:
- port: 9090:80
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:9443:443
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: "360s"
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --no-deploy=traefik
      nodeFilters:
      - server:*
    - arg: --disable=traefik
      nodeFilters:
      - server:*
    - arg: --kube-proxy-arg=metrics-bind-address=0.0.0.0
      nodeFilters:
      - server:*
      - agent:*
    - arg: --kube-scheduler-arg=bind-address=0.0.0.0
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=node-status-update-frequency=4s
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
