kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-demo-vector
networking:
  ipFamily: ipv6
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
- role: worker
- role: worker

